# Generated by Django 2.2.14 on 2022-07-24 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_item_ipfs'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorPayable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=256)),
                ('overdue_usd', models.FloatField()),
            ],
        ),
    ]
