# Generated by Django 2.2.14 on 2022-07-24 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_vendorpayable'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorpayable',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
    ]
